FROM ubuntu:20.04

RUN apt-get update && apt install -y nginx vim
RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf
RUN chown -R www-data:www-data /var/lib/nginx

COPY ./scheduler/django.nginx.conf /etc/nginx/sites-enabled/django

WORKDIR /etc/nginx

RUN mkdir /var/www/html/static

CMD ["nginx"]

EXPOSE 80
EXPOSE 443