FROM python:3.11-alpine

ARG APP_NAME=/app

# 파이썬 설정
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR ${APP_NAME}

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ${APP_NAME}

COPY ./start.sh /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

CMD [ "/start" ]
